### ISSUE TITLE
deepwalk

### ISSUE THREAD

**Issue by baymaxKevin** [alibaba/euler#14]
在用ppi数据测试deepwalk时，遇到如下错误：
Traceback (most recent call last):
  File "scripts/DeepWalk.py", line 59, in <module>
    _, loss, metric_name, metric = model(source)
  File "/usr/local/lib/python2.7/dist-packages/tf_euler/python/layers.py", line 62, in __call__
    outputs = self.call(inputs)
  File "scripts/DeepWalk.py", line 25, in call
    loss, mrr = self.decoder(embedding, embedding_pos, embedding_negs)
  File "scripts/DeepWalk.py", line 50, in decoder
    mrr = tf_euler.metrics.mrr_score(logits, neg_logits)
  File "/usr/local/lib/python2.7/dist-packages/tf_euler/python/metrics.py", line 40, in mrr_score
    all_logits = tf.concat([negative_logits, logits], axis=2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1124, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1033, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 8 and 1. Shapes are [8] and [1]. for 'deepwalk_1/mrr/concat' (op: 'ConcatV2') with input shapes: [128,6,1,8], [128,6,1,1], [] and with computed input tensors: input[2] = <2>.

**Comment by yangsiran** [comment]
@baymaxKevin 修正了[DeepWalk的例子](https://github.com/alibaba/euler/wiki/%E6%A8%A1%E5%9E%8B%E7%BC%96%E5%86%99/_compare/3113bade6552e4d654003c00c6228340f14f9917...3d72b54cbcb34f789de9071e8c03f2a93bfaf026)。

**Comment by baymaxKevin** [comment]
模型已跑通
