### ISSUE TITLE
构建Docker镜像

### ISSUE THREAD

**Issue by cyl1991** [alibaba/euler#197]
谢谢Euler团队的分享。

我在构建Docker镜像的时候，安装tensorflow的那一步会报错。
  Downloading https://mirrors.aliyun.com/pypi/packages/51/ae/9840c4837c6f54034ac942b5344396e8c3d74686a9bd29beafdf633cc221/tensorboard-1.12.2-py2-none-any.whl (3.0MB)
Collecting numpy>=1.13.3 (from tensorflow==1.12)
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://mirrors.aliyun.com/pypi/packages/ff/59/d3f6d46aa1fd220d020bdd61e76ca51f6548c6ad6d24ddb614f4037cf49d/numpy-1.17.4.zip (6.4MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lS7Krk/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lS7Krk/numpy/
The command '/bin/sh -c pip --no-cache-dir install tensorflow==1.12' returned a non-zero code: 1

系统是Ununtu 18，看起来是python版本和numpy版本冲突，请问这个要怎么解决呢？

**Comment by zonghua94** [comment]
这个错误是安装tensorflow的时候自动安装了python3版本的numpy，与当前环境python2.7版本不匹配。所以需要手动安装python2.7版本的numpy，比如：pip install numpy==1.16.5。再安装tensorflow

**Comment by cyl1991** [comment]
这个错误是 按照编译安装里的“构建Docker镜像”，直接执行下面的命令出的错误
it clone --recursive https://github.com/alibaba/euler.git
cd euler
docker build --net=host -f tools/docker/Dockerfile .
