### ISSUE TITLE
RuntimeError: Failed to initialize graph

### ISSUE THREAD

**Issue by kimjh12** [alibaba/euler#210]
I'm following the guide in Getting Started document. After data conversion when I try running following command
>python -m tf_euler \
  --data_dir ppi \
  --max_id 56944 --feature_idx 1 --feature_dim 50 --label_idx 0 --label_dim 121 \
  --model graphsage_supervised --mode train

I encounter error below
>Traceback (most recent call last):
  File "/home/junhwan/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/junhwan/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/junhwan/workspace/euler/tf_euler/__main__.py", line 28, in <module>
    tf.app.run(run_loop.main)
  File "/home/junhwan/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/junhwan/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/junhwan/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/junhwan/workspace/euler/tf_euler/python/run_loop.py", line 405, in main
    run_local(flags_obj, run_network_embedding)
  File "/home/junhwan/workspace/euler/tf_euler/python/run_loop.py", line 366, in run_local
    raise RuntimeError('Failed to initialize graph.')
RuntimeError: Failed to initialize graph.

It might be directory setting problem but I have ppi_data.dat file in euler/ppi directory. Any solutions? Thanks in advance

**Comment by RikonYu** [comment]
i encountered the same problem, and it was because there are files missing from the directory. please check if all of 
ppi-class_map.json
ppi-feats.npy
ppi-G.json
ppi-id_map.json
ppi-walks.txt
ppi_data.dat
ppi_data.json
ppi_meta.json
ppi_test.id
ppi_train.id
ppi_val.id
are present.
