### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by zhouliang1979** [alibaba/euler#289]
我目前系统是 CentOS release 6.2， pip升级到 Successfully installed pip-20.1.1

sudo pip install euler2_gl
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/cmdoptions.py", line 107
    binary_only = FormatControl(set(), {':all:'})
                                               ^
SyntaxError: invalid syntax

**Comment by alinamimi** [comment]
参考一下这个https://github.com/pypa/pip/issues/5341
好像是pip 高版本不支持python2.6了
我这边用pip 9 + python2.7 是可以安装的

**Comment by zhouliang1979** [comment]
[zhouliang3@p44872v ~]$ python -V
Python 2.7.3
[zhouliang3@p44872v ~]$ sudo pip install euler2_gl
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ImportError: No module named pip._internal.cli.main


我重装了2.7版本python， 依旧不行
