### ISSUE TITLE
运行demo时报如下错误：tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/tf_euler/python/euler_ops/libtf_euler.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by hyspe3800** [alibaba/euler#29]
其中tensorflow是源码安装的1.12,euler-gl是pip安装的，运行快速开始的demo时报了如下错误：
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/tf_euler/__init__.py", line 21, in <module>
    from tf_euler.python import encoders
  File "/usr/local/lib/python2.7/dist-packages/tf_euler/python/encoders.py", line 24, in <module>
    from tf_euler.python import euler_ops
  File "/usr/local/lib/python2.7/dist-packages/tf_euler/python/euler_ops/__init__.py", line 20, in <module>
    from tf_euler.python.euler_ops.base import *
  File "/usr/local/lib/python2.7/dist-packages/tf_euler/python/euler_ops/base.py", line 31, in <module>
    _LIB_OP = tf.load_op_library(_LIB_PATH)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/tf_euler/python/euler_ops/libtf_euler.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

**Comment by renyi533** [comment]
我们的pip包是基于TF官方的版本来编译的。怀疑是有二进制不兼容的问题。

您试试基于TF的pip包来实验一下？

或者基于你的TF来编译Euler安装。

**Comment by hyspe3800** [comment]
我先试试编译安装下euler吧

**Comment by pxiuqin** [comment]
@hyspe3800 上述问题解决了吗？

**Comment by hyspe3800** [comment]
> @hyspe3800 上述问题解决了吗？

还没有，网络特别慢，git clone时third party一直失败。。。

**Comment by pxiuqin** [comment]
hyspe3800  我这面尝试删除了以前的TF环境，然后重新使用pip安装euler可以使用

**Comment by hyspe3800** [comment]
编译安装之后还是出现了相同的错误

**Comment by yangsiran** [comment]
@hyspe3800 旧的euler-gl删除了吗？

**Comment by Xiariyouhu** [comment]
我也遇到了同样的问题，我是通过conda安装的tensorflow

**Comment by yangsiran** [comment]
@Xiariyouhu 通过conda安装的tensorflow是1.12吗？如果不是的话，需要从源码编译euler。

**Comment by Xiariyouhu** [comment]
> @Xiariyouhu 通过conda安装的tensorflow是1.12吗？如果不是的话，需要从源码编译euler。

通过conda安装的是1.12，我卸载后用pip重新安装tf，然后编译euler后可以跑了

**Comment by David-AJ** [comment]
> > @Xiariyouhu 通过conda安装的tensorflow是1.12吗？如果不是的话，需要从源码编译euler。
> 
> 通过conda安装的是1.12，我卸载后用pip重新安装tf，然后编译euler后可以跑了

@Xiariyouhu 请问pip重新安装是gpu版本的tf吗？我重装了cpu版的tf可以跑通，但是gpu版本的还是不行
