### ISSUE TITLE
运行"快速开始"的例子时出错

### ISSUE THREAD

**Issue by HongHuangNeu** [alibaba/euler#56]
我的python环境是2.7.5，操作系统是redhat7.2，执行
pip install euler-gl
安装，在运行
https://github.com/alibaba/euler/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
这个例子时，跑到
python ppi_data.py
这一步，报这个错误：

Traceback (most recent call last):
  File "ppi_data.py", line 32, in <module>
    from euler.tools import json2dat
  File "/usr/lib/python2.7/site-packages/euler/__init__.py", line 20, in <module>
    from euler.python.service import *
  File "/usr/lib/python2.7/site-packages/euler/python/service.py", line 27, in <module>
    _LIB = ctypes.CDLL(_LIB_PATH)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory

单机安装还需要配置hdfs么？

**Comment by HongHuangNeu** [comment]
根据https://github.com/alibaba/euler/wiki/%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85
配置hdfs后，不再前面这个错误，开始报下面这个错误：
"段错误(吐核)"

我跑strace  python ppi_data.py ，详细日志如下：


> open("/lib64/libbz2.so.1", O_RDONLY|O_CLOEXEC) = 6
read(6, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\27\0\0\0\0\0\0"..., 832) = 832
fstat(6, {st_mode=S_IFREG|0755, st_size=68192, ...}) = 0
mmap(NULL, 2162024, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 6, 0) = 0x7f4605e48000
mprotect(0x7f4605e57000, 2093056, PROT_NONE) = 0
mmap(0x7f4606056000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 6, 0xe000) = 0x7f4606056000
close(6)                                = 0
mprotect(0x7f4606056000, 4096, PROT_READ) = 0
mprotect(0x7f460626e000, 4096, PROT_READ) = 0
mprotect(0x7f4606473000, 4096, PROT_READ) = 0
mprotect(0x7f4606f96000, 4096, PROT_READ) = 0
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffc07960e90) = -1 ENOENT (No such file or directory)
mprotect(0x7f46066ba000, 8192, PROT_READ) = 0
mprotect(0x7f4606aef000, 4096, PROT_READ) = 0
mprotect(0x7f4606d6d000, 4096, PROT_READ) = 0
mprotect(0x7f460719b000, 4096, PROT_READ) = 0
mprotect(0x7f467da91000, 4096, PROT_READ) = 0
mprotect(0x7f467dbe7000, 4096, PROT_READ) = 0
access("/etc/system-fips", F_OK)        = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x23f0} ---
+++ killed by SIGSEGV (core dumped) +++
段错误(吐核)

**Comment by trendhu** [comment]
（同问）单机安装还需要配置hdfs么？

**Comment by yangsiran** [comment]
> （同问）单机安装还需要配置hdfs么？

现在不需要

**Comment by trendhu** [comment]
> > （同问）单机安装还需要配置hdfs么？
> 
> 现在不需要

可运行时一直显示 No such file or directory 无论我写的是相对路径还是绝对路径

**Comment by rayrayraykk** [comment]
> 
> 
> > （同问）单机安装还需要配置hdfs么？
> 
> 现在不需要

使用pip安装报错libeuler_service.so: cannot open shared object file: No such file or directory
怎么办呢

**Comment by ergouy** [comment]
@rayrayraykk 我的编译安装没成功，用第一种方式安装成功了，但是总是少东西
