### ISSUE TITLE
pip安装找不到libeuler_service.so

### ISSUE THREAD

**Issue by cdj0311** [alibaba/euler#59]
使用pip安装的euler，运行快速开始的模型训练命令时出错如下：
Traceback (most recent call last):
  File "/home/.conda/envs/py2/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/home/.conda/envs/py2/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "tf_euler/__init__.py", line 21, in <module>
    from tf_euler.python import encoders
  File "tf_euler/python/encoders.py", line 23, in <module>
    from tf_euler.python import euler_ops
  File "tf_euler/python/euler_ops/__init__.py", line 20, in <module>
    from tf_euler.python.euler_ops.base import *
  File "tf_euler/python/euler_ops/base.py", line 24, in <module>
    import euler
  File "euler/__init__.py", line 20, in <module>
    from euler.python.service import *
  File "euler/python/service.py", line 27, in <module>
    _LIB = ctypes.CDLL(_LIB_PATH)
  File "/home/.conda/envs/py2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /data1/euler/euler/python/libeuler_service.so: cannot open shared object file: No such file or directory

请问怎么解决？

**Comment by maysina** [comment]
请问这个怎么解决呀？我也找不到这个文件……

**Comment by yangsiran** [comment]
@maysina 您的安装过程和报错日志是什么？

**Comment by rayrayraykk** [comment]
我也是这个错误 请问怎么解决

> 
> 
> @maysina 您的安装过程和报错日志是什么？
