### ISSUE TITLE
Problem with model graphsage

### ISSUE THREAD

**Issue by eecrazy** [alibaba/euler#9]
运行如下命令时报错：
python2 -m tf_euler --data_dir cnet --max_id 40012 --model graphsage --model_dir graphsage --batch_size 256 --learning_rate 0.01 --num_epochs 10  --dim 256  --mode train --log_steps 100 --aggregator mean

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0123 02:46:48.594172  3304 graph_builder.cc:59] Load Done: cnet/CausalNet.dat
I0123 02:46:50.339694  3304 graph_builder.cc:109] Done: build all sampler
I0123 02:46:50.339740  3304 graph_builder.cc:112] Graph build finish
WARNING:tensorflow:From /home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/layers.py:77: __init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalentbehavior.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from graphsage/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into graphsage/model.ckpt.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/__main__.py", line 28, in<module>
    tf.app.run(run_loop.main)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line340, in main
    run_local(flags_obj, run_network_embedding)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line303, in run_local
    run(flags_obj, master='', is_chief=True)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line292, in run_network_embedding
    run_train(model, flags_obj, master, is_chief)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line139, in run_train
    sess.run(train_op)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[node graphsage_1/sageencoder_1/Reshape_7 (defined at /home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/encoders.py:125)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](graphsage_1/sageencoder_1/GetDenseFeature_1, graphsage_1/sageencoder_2/Reshape_7/shape)]]

Caused by op u'graphsage_1/sageencoder_1/Reshape_7', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/__main__.py", line 28, in<module>
    tf.app.run(run_loop.main)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line340, in main
    run_local(flags_obj, run_network_embedding)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line303, in run_local
    run(flags_obj, master='', is_chief=True)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line292, in run_network_embedding
    run_train(model, flags_obj, master, is_chief)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/run_loop.py", line107, in run_train
    _, loss, metric_name, metric = model(source)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/layers.py", line 62, in __call__
    outputs = self.call(inputs)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/models/base.py", line 99, in call
    embedding = self.target_encoder(src)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/models/graphsage.py", line 58, in target_encoder
    return self._target_encoder(inputs)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/layers.py", line 62, in __call__
    outputs = self.call(inputs)
  File "/home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/encoders.py", line125, in call
    h = aggregator((hidden[hop], tf.reshape(hidden[hop + 1], neigh_shape)))
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6482, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/zyli/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[node graphsage_1/sageencoder_1/Reshape_7 (defined at /home/zyli/.local/lib/python2.7/site-packages/tf_euler/python/encoders.py:125)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](graphsage_1/sageencoder_1/GetDenseFeature_1, graphsage_1/sageencoder_2/Reshape_7/shape)]]

应该是encoders.py:125报错，cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero. 我对tensorflow不熟悉，请问该怎么修复？

**Comment by yangsiran** [comment]
@eecrazy model为graphsage的时候需要指定`--label_idx`和`--label_dim`这两个选项，不然特征取出来就是空的了。

**Comment by yangsiran** [comment]
@pxiuqin 请问你的euler是从PYPI上安装的吗？以及运行的TensorFlow的版本是什么？

**Comment by pxiuqin** [comment]
@yangsiran 已经解决

**Comment by F36** [comment]
> @eecrazy model为graphsage的时候需要指定`--feature_idx`和`--feature_dim`这两个选项，不然特征取出来就是空的了。

这两个必须得指定吗？我没有用到任何特征，只是学习图中节点之间的关系，请问如何解决？

**Comment by LeenaShekhar** [comment]
@pxiuqin Could you please tell me how did you resolve that? I get the same error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/home/leshekha/euler/tf_euler/__init__.py", line 21, in <module>
    from tf_euler.python import encoders
  File "/home/leshekha/euler/tf_euler/python/encoders.py", line 23, in <module>
    from tf_euler.python import euler_ops
  File "/home/leshekha/euler/tf_euler/python/euler_ops/__init__.py", line 20, in <module>
    from tf_euler.python.euler_ops.base import *
  File "/home/leshekha/euler/tf_euler/python/euler_ops/base.py", line 31, in <module>
    _LIB_OP = tf.load_op_library(_LIB_PATH)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /data/home/leshekha/euler/tf_euler/python/euler_ops/libtf_euler.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

I have Tensorflow version, '1.12.0'.

**Comment by nwf5d** [comment]
> @yangsiran 已经解决

怎么解决的呢？
